services:
  app:
    build:
      context: ./spliit
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy

      traefik.http.routers.spliit-app.rule: Host(`${SPLIIT_DOMAIN}`)
      traefik.http.routers.spliit-app.entrypoints: websecure

      traefik.http.routers.spliit-app.tls: "true"
      traefik.http.routers.spliit-app.tls.certresolver: leresolver

      traefik.http.routers.spliit-app.service: spliit-app-svc
      traefik.http.services.spliit-app-svc.loadbalancer.server.port: "3000"

      traefik.http.routers.spliit-app.middlewares: authelia@docker

      homepage.group: Other
      homepage.name: Spliit
      homepage.icon: https://github.com/spliit-app/spliit/blob/main/public/logo-with-text.png?raw=true
      homepage.href: https://${SPLIIT_DOMAIN}

    networks:
      - proxy
      - local
      - homepage-net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - spliit-db:/var/lib/postgresql/data
    networks:
      - local
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  proxy:
    external: true
  homepage-net:
    external: true
  local:


volumes:
  spliit-db:
    external: true
