---
services:
  ocis:
    depends_on:
      drawio-init:
        condition: service_completed_successfully

  drawio-init:
    image: owncloud/web-extensions:draw-io-0.3.0
    user: root
    volumes:
      - ocis-apps:/apps
    labels:
      # set watchtower to monitor only and do not perform the update
      com.centurylinklabs.watchtower.monitor-only: "true"
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/draw-io/ /apps"]
