---
services:
  ocis:
    depends_on:
      progressbars-init:
        condition: service_completed_successfully

  progressbars-init:
    image: owncloud/web-extensions:progress-bars-0.3.0
    user: root
    volumes:
      - ocis-apps:/apps
    labels:
      # set watchtower to monitor only and do not perform the update
      com.centurylinklabs.watchtower.monitor-only: "true"
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/progress-bars/ /apps"]
