---
services:
  ocis:
    depends_on:
      unzip-init:
        condition: service_completed_successfully

  unzip-init:
    image: owncloud/web-extensions:unzip-0.4.0
    user: root
    volumes:
      - ocis-apps:/apps
    labels:
      # set watchtower to monitor only and do not perform the update
      com.centurylinklabs.watchtower.monitor-only: "true"
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/unzip/ /apps"]
