services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: MySpeed
    ports:
      - "4674:5216"
    volumes:
      - myspeed:/myspeed/data
    restart: unless-stopped
    labels:
      homepage.group: Network
      homepage.name: Speedtest tracker
      homepage.icon: si-speedtest.svg
      homepage.href: http://localhost:4674
      homepage.widget.type: myspeed
      homepage.widget.url: http://myspeed:5216
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      homepage-net:

volumes:
  myspeed:

networks:
  homepage-net:
    external: true
