services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      proxy:
        aliases:
          - ${OCIS_DOMAIN}
          - ${WOPISERVER_DOMAIN}
          - ${COLLABORA_DOMAIN}
          - ${ONLYOFFICE_DOMAIN}
          - ${JELLYFIN_DOMAIN}
          - ${WALLABAG_DOMAIN}
      homepage-net:
    command:
      - '--api=true'
      #- '--pilot.dashboard=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'

      - '--log=true'
      - '--log.level=INFO'

      - '--providers.docker=true'
      #- --providers.docker.endpoint=unix:///var/run/docker.sock
      - '--providers.docker.exposedByDefault=false'

      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=${EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/certs/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true

      - '--accesslog=true'
      - '--accessLog.filePath=/var/log/access.log'
      - '--accessLog.filters.statusCodes=400-499'

      - '--entryPoints.web=true'
      - '--entrypoints.web.address=:80'

      - '--entryPoints.websecure=true'
      - '--entrypoints.websecure.address=:443'

      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--ocsp=true'

      #- '--entryPoints.web.forwardedHeaders.insecure=false'
      #- '--entryPoints.web.proxyProtocol.insecure=false'

      #- '--entryPoints.websecure.forwardedHeaders.insecure=false'
      #- '--entryPoints.websecure.proxyProtocol.insecure=false'

      #- '--entryPoints.http.address=:8080/tcp'

      ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
      # - '--entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'
      # - '--entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'


      #- '--entryPoints.https.address=:8443/tcp'
      ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
      # - '--entryPoints.https.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'
      # - '--entryPoints.https.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'

    ports:
      - "443:443"
    volumes:
      - ./logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/certs/
      - ./dynamic:/etc/traefik/dynamic:ro
    labels:
      # Enable Traefik and specify network
      traefik.enable: "true"
      traefik.docker.network: proxy

      # Define the router for Traefik dashboard
      traefik.http.routers.traefik.rule: "Host(`${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.traefik.entrypoints: websecure

      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: leresolver

      traefik.http.routers.traefik.service: api@internal

      # Attach Authentik authentication middleware and secure headers to the Traefik router
      traefik.http.routers.traefik.middlewares: authelia@docker,secure-headers@file



      homepage.group: Network
      homepage.name: Traefik
      homepage.icon: traefik.svg
      homepage.href: https://${TRAEFIK_DOMAIN}
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped

volumes:
  certs:

networks:
  proxy:
    external: true
  homepage-net:
    external: true
