
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "7534:8080" # webapp
      - "7535:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
    networks:
      homepage-net:
    labels:
      homepage.group: Update & Monitor
      homepage.name: Scrutiny
      homepage.icon: scrutiny.svg
      homepage.href: http://localhost:7534/
      homepage.widget.type: scrutiny
      homepage.widget.url: http://scrutiny:8080
    restart: unless-stopped
    logging:
      driver: "local"

networks:
  homepage-net:
    external: true
