services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      homepage-net:
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    networks:
      proxy:
    environment:
      BASE_URL: ${PUBLIC_HOMEPAGE_DOMAIN}
      # TODO move to .env (?)
      SECRET_ENCRYPTION_KEY: 03b507e0f8ece816e0bc72c90370341df0467c4303d754278f4786efddba23d0
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    ports:
      - '7575:7575'
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`${PUBLIC_HOMEPAGE_DOMAIN}`)"
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls.certresolver: leresolver
      traefik.http.routers.homepage.tls: "true"
      traefik.http.services.homepage.loadbalancer.server.port: "7575"
      traefik.http.routers.homepage.middlewares: secure-headers@file

    restart: unless-stopped

networks:
  proxy:
    external: true
  homepage-net:
    external: true
