{
 "title": "Traefik",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  { "title": "global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "rate(traefik_service_requests_total[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "$backend stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$service return code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_service_requests_total{service=\"$service\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) / sum(traefik_service_requests_total{service=\"$service\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total requests over 5min $service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "Total requests $service"
    }
   ]
  },
  {
   "title": "other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Status code 200 of entrypoint over 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~ \"$entrypoint\"}[5m])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  }
 ]
}