services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PGID: "1002"
      PUID: "1002"
      TZ: Europe/Rome
      WEBUI_PORT: "8078"
    volumes:
      - qbit-config:/config
      - qbit-torrents:/torrents
      - media-lib:/data
      - ./engines:/config/qBittorrent/nova3/engines
    ports:
      - 8078:8078
      - 6881:6881
      - 6881:6881/udp
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: qbittorrent
      homepage.icon: qbittorrent.svg
      homepage.href: http://localhost:8078
      homepage.widget.type: qbittorrent
      homepage.widget.url: http://qbittorrent:8078
      homepage.widget.username: ${QBITTORRENT_USERNAME}
      homepage.widget.password: ${QBITTORRENT_PASSWORD}
    logging:
      driver: local
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      AUTO_UPDATE: "true"
      PGID: "1002"
      PUID: "1002"
      TZ: Europe/Rome
        #optional
        #- RUN_OPTS=<run options here> #optional
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: Jackett
      homepage.icon: jackett.svg
      homepage.href: http://localhost:9117
      homepage.widget.type: jackett
      homepage.widget.url: http://jackett:9117
    logging:
      driver: "local"
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: "false"
      LOG_LEVEL: info
      TZ: Europe/Rome
    ports:
      - 8191:8191
    networks:
      media:
    logging:
      driver: local
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      PGID: "1002"
      PUID: "1002"
      TZ: Europe/Rome
      UMASK: "002"
    volumes:
      - prowlarr-config:/config
    ports:
      - "9696:9696"
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: Prowlarr
      homepage.icon: prowlarr.svg
      homepage.href: http://localhost:9696
      homepage.widget.type: prowlarr
      homepage.widget.url: http://prowlarr:9696
      homepage.widget.key: ${PROWLARR_API_KEY}
    logging:
      driver: "local"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PGID: "1002"
      PUID: "1002"
      TZ: Europe/Rome
      UMASK: "002"
    volumes:
      - sonarr-config:/config
      - media-lib:/data
    ports:
      - "8989:8989"
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: Sonarr
      homepage.icon: sonarr.svg
      homepage.href: http://localhost:8989
      homepage.widget.type: sonarr
      homepage.widget.url: http://sonarr:8989
      homepage.widget.key: ${SONARR_API_KEY}
    logging:
      driver: "local"
    restart: unless-stopped

  radarr:
    image: cr.hotio.dev/hotio/radarr
    container_name: radarr
    environment:
      PGID: "1002"
      PUID: "1002"
      TZ: Europe/Rome
      UMASK: "002"
    volumes:
      - radarr-config:/config
      - media-lib:/data
    ports:
      - "7878:7878"
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: Radarr
      homepage.icon: radarr.svg
      homepage.href: http://localhost:7878
      homepage.widget.type: radarr
      homepage.widget.url: http://radarr:7878
      homepage.widget.key: ${RADARR_API_KEY}
    logging:
      driver: "local"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - UMASK=002
    volumes:
      - readarr-config:/config
      - media-lib:/data
    ports:
      - "8787:8787"
    networks:
      media:
      homepage-net:
    labels:
      homepage.group: servarr
      homepage.name: readarr
      homepage.icon: readarr.svg
      homepage.href: http://localhost:8787
      homepage.widget.type: readarr
      homepage.widget.url: http://readarr:8787
      homepage.widget.key: ${READARR_API_KEY}
    logging:
      driver: "local"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      LOG_LEVEL: debug
      TZ: Europe/Rome
    ports:
      - 5055:5055
    networks:
      media:
      proxy:
      homepage-net:
    volumes:
      - ./jellyseerr_logs:/app/config/logs
      - jellyseerr-config:/app/config
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy

      traefik.http.routers.jellyseerr.rule: "Host(`${JELLYSEERR_DOMAIN}`)"
      traefik.http.routers.jellyseerr.entryPoints: websecure

      traefik.http.routers.jellyseerr.tls.certresolver: leresolver
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.routers.jellyseerr.service: jellyseerr-svc
      traefik.http.services.jellyseerr-svc.loadbalancer.server.port: "5055"

      homepage.group: Media
      homepage.name: Discover
      homepage.icon: jellyseerr.svg
      homepage.href: https://${JELLYSEERR_DOMAIN}
      homepage.widget.type: jellyseerr
      homepage.widget.url: http://jellyseerr:5055
      homepage.widget.key: ${JELLYSEERR_API_KEY}
    logging:
      driver: "local"
    restart: unless-stopped

networks:
  media:
    external: true
  proxy:
    external: true
  homepage-net:
    external: true


volumes:
  qbit-config:
    external: true
  qbit-torrents:
    external: true
  jackett-config:
    external: true
  jackett-downloads:
    external: true
  prowlarr-config:
    external: true
  sonarr-config:
    external: true
  radarr-config:
    external: true
  readarr-config:
    external: true
  jellyseerr-config:
    external: true
  media-lib:
    external: true
